### ISSUE TITLE
Additions to `PathRef`

### ISSUE THREAD

**Issue by dsherret** [dsherret/dax#105]
* ~~`components(): Iterator<string>`~~
* ~~`startsWith(text: string | PathRef | URL): boolean;`~~
* ~~`endsWith(text: string): boolean;`~~
* ~~`equals(path: string | URL | PathRef): boolean;`~~
* `linkTo / linkToSync` methods (copy `symlinkTo`)

**Comment by Yohe-Am** [comment]
Some ideas:
- [Copy directories](https://deno.land/std@0.188.0/fs/mod.ts?s=copy)
- Remove if exists or suppress error if NOENT

**Comment by dsherret** [comment]
@Yohe-Am I think copying directories is implemented now. Let's open specific issues for specific features from now on. By `removeSafe`, do you just mean a method that would not throw when the file doesn't exit?

**Comment by Yohe-Am** [comment]
> `removeSafe`, not throw when file doesn't exists

Yep, exactly that. `removeIfExists` or `ensureDeleted` some ways it could be named.
