### ISSUE TITLE
Keep new lines in commands?

### ISSUE THREAD

**Issue by sigmaSd** [dsherret/dax#153]
Currently commands seems to not keep new lines in string literals, the workaround is to use quotes inside, is this by design ?

```ts
import { $ } from "./mod.ts";

await $`echo hello
world`; // the new line here becomes a space
console.log("------------------------------");
await $`echo "hello\nworld"`;
```
result
```
hello world
------------------------------
hello
world
```

**Comment by dsherret** [comment]
Yeah, that's by design. The first command is passing two arguments (`["hello", "world"]`) and the second is passing one (`["hello\world"]`).
