### ISSUE TITLE
Appreciation 

### ISSUE THREAD

**Issue by matklad** [dsherret/dax#174]
The opposite of an issue --- just want praise the excellent design of this library! "embedded 'shell' scripting DSL" is a popular genre for convenience libraries, but usually such libraries provide messy, footguny API. You do everything right!

* Using JS template string literals to safely construct argv array without the risk of shell injection (really, [_everyone_](https://lobste.rs/s/9yu5sl/after_discussion_here_i_created_lib_for#c_ckkova) gets this one wrong)
* Spawning processes directly, rather than using host-specific `/bin/sh`
* Using your own, cross platform shell syntax parser (via deno_task_shell)
* Providing a suite of cross-platform utilities like `mkdir` and `rm`
* Automatically waiting for children, so that ``$`/bin/sleep 10`.spawn();`` doesn't leak a process (this one in particular is subtle, and yet so :fire:)

**Comment by dsherret** [comment]
Thanks @matklad! Means a lot. Thanks for the feedback and I'm happy you're using it :)
