### ISSUE TITLE
output redirection in command throws "Async commands are not supported" error

### ISSUE THREAD

**Issue by wvh** [dsherret/dax#179]
Hello!

This command:
```js
await $`echo 1 && echo stderr >&2`;
```

throws this error:
```
error: Uncaught (in promise) Error: Async commands are not supported. Run a command concurrently in the JS code instead.
      throw new Error("Async commands are not supported. Run a command concurrently in the JS code instead.");
```

This is not an async command, I guess the ampersand is misinterpreted as a background task operator?

Shouldn't it be possible to pass through the redirection to the shell and allow the command to write to `STDERR` this way? At least writing a simple shell script one-liner that writes to `STDERR` properly catches the output, so this is just about the initial command set-up.

Thanks for your time!

**Comment by sigmaSd** [comment]
dax doesn't support redirection and `>&2` syntax, you'll have to use `.stdout("piped").stderr("piped")` and extract the result and merge it manually.

**Comment by pomdtr** [comment]
It would be nice to be able to do:

`echo 1`.stdout(Deno.stderr.writable)

**Comment by dsherret** [comment]
@pomdtr that's possible nowadays.

**Comment by pomdtr** [comment]
I can imagine, I created the PR (https://github.com/dsherret/dax/pull/184).

thanks for merging it btw !

**Comment by dsherret** [comment]
Hah! Thanks again 😄
