### ISSUE TITLE
Make it easier to pipe to files

### ISSUE THREAD

**Issue by matklad** [dsherret/dax#206]
I am having trouble figuring out how to pipe command's stderr to a file :)

Here's the code I arraivied at:

```ts
const child = $`my-command`.stderr('piped').spawn();
child.stderr().pipeTo((await Deno.open("log.vopr")).writable)
await child
```

This typechecks, but throws at runtime ` Error: Bad file descriptor (os error 9)`, and it requires reaching for raw `Deno.open` APIs. As far as I understand, it isn't actually possible to do that with `$.path` API (or I am utterly failing at finding this in the API surface). 

Ideally, I'd love to write just

```ts
await $`my-command`.stderr($.path("log.vopr"));
```

Not sure whether there's a gap in the API surface or in my doc reading abilities :) 

(note: I really want to pipe there, as the output is gigs in size)

**Comment by dsherret** [comment]
Yeah, it's not very good atm (my knowledge of pipes in JS when I wrote this was not good). This works for me in the latest version:

```ts
import $ from "https://deno.land/x/dax@0.36.0/mod.ts";

const txtFile = $.path("test.txt");
using file = txtFile.createSync();
await $`deno eval 'console.error(1); setTimeout(() => console.error(2), 2000);'`
  .env("NO_COLOR", "1")
  .stderr(file);
```

(I should update the docs with an example showing this... it's not in the docs)

> `await $`my-command`.stderr($.path("log.vopr"));`

Yeah, that would be good because it could also handle automatically closing the file when the command is done.

**Comment by matklad** [comment]
Ah, right, indeed its the case of me being lost in the API maze! I guess I can name a couple stumbling blocks:

* the `.stderr(` parameter, if I recall, has to be a `WriterSync`, and that made me falsely assume that I wouldn't be able to just pass a file here, as I expected the relevant API to be asynchronous. That's why I started reaching out for spawn.
* besides _assuming_ that file can't be `WriterSync`, I tried to search for relevant "impls", but failed:
  - in VS Code, because it is a dependency, I can't use "whole project text search" to just look for relevant functions acrosss files in the library
  - the API docs are not particularly useful either https://deno.land/x/dax@0.36.0/mod.ts?s=WriterSync

Not sure if theer's anything actionable here. Maybe defining `ShellPipeWriterKind` as

```
| "inherit"
| "null"
| "piped"
| "inheritPiped"
| WriterSync
| FsFileWrapper
```

which is of course redundant, but also clearly signals to the user "hey, you could pass in a file here".

**Comment by dsherret** [comment]
In 0.38.0 it's now possible to do:

```ts
await $`my-command 2> log.vopr`;
// or specified via a PathRef (ex. `$.path("somePath")`)
await $`my-command 2> ${pathRef}`;
```
