### ISSUE TITLE
Patch for deprecation warnings in console/utils.ts

### ISSUE THREAD

**Issue by cseidr** [dsherret/dax#208]
Hello

Here's a quick patch for deprecation warnings in console/utils.ts. The tests pass. That's the only guarantee :-)
Thanks for a great product we use in production.

[dep.patch](https://github.com/dsherret/dax/files/14056177/dep.patch)

**Comment by dsherret** [comment]
Thanks @cseidr! Would you like to open a PR? I can do it otherwise.

**Comment by cseidr** [comment]
here is a PR :-) 
https://github.com/dsherret/dax/pull/209
