### ISSUE TITLE
`deno compile` into executable with `dax`

### ISSUE THREAD

**Issue by dolbyzerr** [dsherret/dax#275]
I am trying to use `dax` to build an internal cli. 

Minimal example is
```dax_test.ts
import $ from "@david/dax"

const output = await $`echo "hello world"`.text() 
console.log(output)
```

```sh
deno compile --allow-all dax_test.ts && ./dax_test
```

It compiles just fine but when I try to execute `./dax_test` it just hangs without any error.

Is it something that I am doing wrong?

**Comment by dolbyzerr** [comment]
Interestingly enough it's working with deno bundle -> deno compile

```bash
deno bundle main.ts
deno compile --allow-env --allow-read --allow-write --allow-net --output bin/main-bundled main.js
./bin/main-bundled # hello world
```

I've created a simple repo to demonstrate https://github.com/dolbyzerr/deno-dax-compile-test

I suspect that it's related to wasm module but not really sure.

**Comment by NfNitLoop** [comment]
FWIW, this is working for me:

```
> deno --version
deno 1.44.2 (release, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5
```

```
> bin/main-bundled
hello world
> bin/main
hello world
```

**Comment by dolbyzerr** [comment]
🤔 it's working for me as well now, not sure what changed but must be something with my system

@NfNitLoop thanks for checking!
