### ISSUE TITLE
Walk methods are no longer available

### ISSUE THREAD

**Issue by greentore** [dsherret/dax#288]
I can no longer use dax to walk directories since v0.42.0 when the path module was moved to a separate package. Is that expected?

**Comment by dsherret** [comment]
Sorry I should have documented that change. I wasn't sure how much it was used and thought it was maybe too much to have on a general path class.

You can get this functionality easily by using the walk module in std/fs directly: https://jsr.io/@std/fs@1.0.3/doc/walk/~
