### ISSUE TITLE
Add an api to download files to disk

### ISSUE THREAD

**Issue by sigmaSd** [dsherret/dax#54]
Maybe it could be another override to request  

the advantage it would skip loading the file into memory while keeping the cool progress bar

**Comment by sigmaSd** [comment]
With fetch I can do 
```ts
 const imageFile = Deno.createSync(imagePath);
await fetch(imageUrl).then((r) => r.body?.pipeTo(imageFile.writable));
```
but request doesn't seem to expose body in the response

**Comment by dsherret** [comment]
Good idea! There will be a `pipeToPath` method in the next release along with `pipeTo` and `pipeThrough` methods.

**Comment by sigmaSd** [comment]
thanks really cool!

**Comment by sigmaSd** [comment]
what about making pipeToPath defaults to figuring out the path from the url `url.pathname.split('/').at(-1)` I think wget act like this?

**Comment by dsherret** [comment]
I was wondering about it too and it seems reasonable. The one thing I wasn't sure about was what to do for a path that's just a domain like `https://deno.land` (so `/`)... I think in those cases it should just throw? Would you like to open a PR for that? Otherwise I can get to it soon.

**Comment by sigmaSd** [comment]
I'm not sure about the idea either, the current api you implemented is very clear though, maybe we give it some time and wait for more interesting use cases?

**Comment by dsherret** [comment]
I ended up implementing it in #59

**Comment by sigmaSd** [comment]
Nice
