### ISSUE TITLE
Feature request: Pluggable commands

### ISSUE THREAD

**Issue by pocketken** [dsherret/dax#7]
It would be really handy if we could extend the shell command parser out with support for additional, user-defined commands.  For my current use case, for example, it'd be great to be able to provide Deno-based drop-ins for things like `gzip`, `tar` and so on, but you probably don't want every possible command under the sun within dax itself...?

I know our vet has complained about my cats getting a little too fat, anyway...

**Comment by dsherret** [comment]
I like that idea and I think it plays well with the `CommandBuilder` https://github.com/dsherret/dax#commandbuilder and custom `$`.

**Comment by dsherret** [comment]
Implemented in #8.
